name = "abdooll110"
main = "index.js"
compatibility_date = "2025-11-09"
workers_dev = true
preview_urls = true
# logpush job is setup to capture from envs ending: log, pro, or one
logpush = false
# use node_compat or custom build
# node_compat = true
send_metrics = false
minify = false

[vars]
UUID = "a1db2e96-c848-4f19-bda7-ad3e8dc40259"
PROXYIP = "nima.nscl.ir"

# [build]
# command = "npm run deploy"

# [[rules]]
# type = "ESModule"
# globs = ["**/*.js"]
